version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-wrapper-{{ .Environment.CIRCLE_JOB }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v1-gradle-wrapper-{{ .Environment.CIRCLE_JOB }}
            - v1-gradle-wrapper-
      - restore_cache:
          keys:
            - v1-gradle-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "build.gradle" }}
            - v1-gradle-cache-{{ .Environment.CIRCLE_JOB }}
            - v1-gradle-cache-
      - run: ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ .Environment.CIRCLE_JOB }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "build.gradle" }}